set IDENTITY_INSERT marcas on;

INSERT INTO marcas (id_marca, nombre_marca, estado_marca)
VALUES 
(1, 'Intel', 'alta'),
(2, 'AMD', 'alta'),
(3, 'NVIDIA', 'alta'),
(4, 'ASUS', 'alta'),
(5, 'MSI', 'alta'),
(6, 'Gigabyte', 'alta'),
(7, 'Corsair', 'alta'),
(8, 'Kingston', 'alta'),
(9, 'Samsung', 'alta'),
(10, 'Seagate', 'alta'),
(11, 'Western Digital', 'alta'),
(12, 'Crucial', 'alta'),
(13, 'Cooler Master', 'alta'),
(14, 'EVGA', 'alta'),
(15, 'Thermaltake', 'alta'),
(16, 'Logitech', 'alta'),
(17, 'Razer', 'alta'),
(18, 'HP', 'alta'),
(19, 'Canon', 'alta'),
(20, 'Epson', 'alta'),
(21, 'Acer', 'alta'),
(22, 'Dell', 'alta'),
(23, 'Lenovo', 'alta'),
(24, 'Toshiba', 'alta'),
(25, 'Sony', 'alta'),
(26, 'Philips', 'alta'),
(27, 'LG', 'alta'),
(28, 'BenQ', 'alta'),
(29, 'ASRock', 'alta'),
(30, 'Noctua', 'alta'),
(31, 'Be Quiet!', 'alta'),
(32, 'HyperX', 'alta'),
(33, 'SteelSeries', 'alta'),
(34, 'Patriot', 'alta'),
(35, 'ADATA', 'alta'),
(36, 'Zotac', 'alta'),
(37, 'Sapphire', 'alta'),
(38, 'Pny', 'alta'),
(39, 'Rosewill', 'alta'),
(40, 'Antec', 'alta');